# dbitseq

In [1]:
import anndata as ad
import numpy as np
import scanpy as sc
import pandas as pd


import seaborn as sns
from collections import Counter
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import sys
sys.path.append('..')
import matplotlib.pyplot as plt
from sklearn.metrics import adjusted_rand_score

from src.interface import UnitedNet
from src.configs import *
from scipy.stats import spearmanr, pearsonr

In [2]:
def split_data(test_batch):
    adata_rna_train = adata_rna_all[adata_rna_all.obs['batch'] != test_batch]
    adata_morph_train = adata_morph_all[adata_morph_all.obs['batch'] != test_batch]
    adata_mrna_niche_train = adata_mrna_niche_all[adata_mrna_niche_all.obs['batch'] != test_batch]

    adata_rna_test = adata_rna_all[adata_rna_all.obs['batch'] == test_batch]
    adata_morph_test = adata_morph_all[adata_morph_all.obs['batch'] == test_batch]
    adata_mrna_niche_test = adata_mrna_niche_all[adata_mrna_niche_all.obs['batch'] == test_batch]

    return [adata_rna_train, adata_morph_train, adata_mrna_niche_train], [adata_rna_test, adata_morph_test,
                                                                          adata_mrna_niche_test]


def concat_adatas(adatas_train, adatas_test):
    return [ad.concat([adata_train, adata_test]) for adata_train, adata_test in zip(adatas_train, adatas_test)]


def save_umap(adata_all,label,test_batch,nametype):
  fig,ax = plt.subplots(figsize=(6,4))
  ax=sc.pl.umap(adata_all,color=label, ax=ax,show=False)
  fig.savefig(root_save_path+f'/plot/{test_batch}_{nametype}_{label}.png',dpi=300)
  

def generate_adata(data, nonnan_indices, cell_type_label, cols, rows, batch):
    data = data.loc[data.index[nonnan_indices]]
    adata=ad.AnnData(X=np.array(data),obs=list(data.index))
    adata.obs['label']  = cell_type_label
    adata.obs['imagecol'] = cols
    adata.obs['imagerow'] = rows
    adata.obs['batch']  = batch
    return adata

In [3]:
from sklearn import preprocessing
def change_label(adata,batch):
    adata.obs['batch'] = batch
    adata.obs['imagecol'] = adata.obs['array_col']
    adata.obs['imagerow'] = adata.obs['array_row']
    adata.obs['label'] = adata.obs['cell_type']
    return adata

In [4]:
def pre_ps(adata_list,sc_pre = None):
    adata_list_all = [ad_x.copy() for ad_x in adata_list]
    scalars = []
    assert (adata_list_all[0].X>=0).all(), "poluted input"
    for idx, mod in enumerate(adata_list_all):
        t_x = mod.X
        if sc_pre != None:
            scaler = sc_pre[idx]
        else:
            scaler = preprocessing.StandardScaler().fit(t_x)
        t_x = scaler.transform(t_x)
        mod.X = t_x
        adata_list_all[idx] = mod
        scalars.append(scaler)

    return adata_list_all,scalars

# load dbitseq data

In [5]:
technique = 'dbitseq'
data_path = f"../data/{technique}"
device = "cuda:0"

In [6]:
adata_niche_rna_train = sc.read_h5ad(f'{data_path}/adata_niche_rna_train.h5ad')
adata_niche_rna_test = sc.read_h5ad(f'{data_path}/adata_niche_rna_test.h5ad')

adata_rna_train = sc.read_h5ad(f'{data_path}/adata_rna_train.h5ad')
adata_rna_test = sc.read_h5ad(f'{data_path}/adata_rna_test.h5ad')

adata_protein_train = sc.read_h5ad(f'{data_path}/adata_protein_train.h5ad')
adata_protein_test = sc.read_h5ad(f'{data_path}/adata_protein_test.h5ad')


In [7]:
adata_rna_train = change_label(adata_rna_train,'train')
adata_protein_train=change_label(adata_protein_train,'train')
adata_niche_rna_train=change_label(adata_niche_rna_train,'train')

adata_rna_test = change_label(adata_rna_test,'test')
adata_protein_test = change_label(adata_protein_test,'test')
adata_niche_rna_test = change_label(adata_niche_rna_test,'test')

adatas_train = [adata_rna_train, adata_protein_train, adata_niche_rna_train]
adatas_test = [adata_rna_test, adata_protein_test, adata_niche_rna_test]

adatas_all = []
for ad_train, ad_test in zip(adatas_train,adatas_test):
    ad_all = ad_train.concatenate(ad_test,batch_key='sample')
    ad_all = change_label(ad_all,'test')
    adatas_all.append(ad_all)
adatas_all,_ = pre_ps(adatas_all)    
    

adatas_train,_ = pre_ps(adatas_train)   
adatas_test,_ = pre_ps(adatas_test)   


C:\Users\xit882\.conda\envs\pytorch\lib\site-packages\anndata\_core\anndata.py:1785: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  [AnnData(sparse.csr_matrix(a.shape), obs=a.obs) for a in all_adatas],


# Train and finetune UnitedNet

In [13]:

if train_model:
    technique = 'dbitseq'
    data_path = f"../data/{technique}"
    root_save_path = f"../saved_results/dlpfc"
    model = UnitedNet(root_save_path, device=device, technique=dbitseq_config)
    model.train(adatas_train,verbose=True)
    model.finetune(adatas_all,verbose=True)
else:
    technique = 'dbitseq'
    data_path = f"../data/{technique}"
    root_save_path = f"../saved_results/dlpfc"
    model = UnitedNet(root_save_path, device=device, technique=dbitseq_config)



training


  0%|                                                                                                                                                                                                           | 0/20 [00:00<?, ?it/s]



Losses                    Value
-------------------  ----------
translation_loss     0.835885
discriminator_loss   0.0500271
generator_loss       0.0238487
contrastive_loss     0.00538122
reconstruction_loss  0.721778
best_head            9
best model saved at ../saved_results/dlpfc/train_best.pt 



  5%|█████████▊                                                                                                                                                                                         | 1/20 [00:10<03:12, 10.15s/it]



Metrics    Value
---------  -------------------------------------------------------
r2         [[ 6.12120218e-04 -1.13636726e-03  6.90314419e-04]
            [ 6.34486624e-01  7.96618184e-01  3.45287377e-01]
            [ 6.66547313e-03 -1.30406882e-03  3.74370256e-02]]
confusion  [[  0   0   0   0  81   0   0   0   0   0   0   0   0]
            [  0   0   0   0  83   0   0   0   0   0   0   0   0]
            [  0   0   0   0 124   0   0   0   0   0   0   0   0]
            [  0   0   0   0 121   0   0   0   0   0   0   0   0]
            [  0   0   0   0 165   0   0   0   0   0   0   0   0]
            [  0   0   0   0  72   0   0   0   0   0   0   0   0]
            [  0   0   0   0  17   0   0   0   0   0   0   0   0]
            [  0   0   0   0   6   0   0   0   0   0   0   0   0]
            [  0   0   0   0   9   0   0   0   0   0   0   0   0]
            [  0   0   0   0  44   0   0   0   0   0   0   0   0]
            [  0   0   0   0  18   0   0   0   0   0   1   0   0]
 

 10%|███████████████████▌                                                                                                                                                                               | 2/20 [00:19<02:52,  9.57s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.02600608 0.00553089 0.02326392]
            [0.76770328 0.82644394 0.39506198]
            [0.15660905 0.02117366 0.2393308 ]]
confusion  [[33  0 30 13  1  4  0  0  0  0  0  0  0]
            [ 6 18 22  3 17 16  1  0  0  0  0  0  0]
            [ 4  4 61 19 24 11  1  0  0  0  0  0  0]
            [15  0 55 14 34  1  0  0  0  2  0  0  0]
            [ 8  1 22 10 74 49  0  0  0  0  1  0  0]
            [ 0  6 10  2 28 25  0  0  0  1  0  0  0]
            [11  0  6  0  0  0  0  0  0  0  0  0  0]
            [ 1  0  0  1  1  3  0  0  0  0  0  0  0]
            [ 0  0  7  2  0  0  0  0  0  0  0  0  0]
            [13  0 11  1 13  0  0  0  0  4  2  0  0]
            [ 9  0  8  0  0  0  0  0  0  0  2  0  0]
            [ 0  0  2  2  0  0  0  0  0  0  0  0  0]
            [ 0  0  1  0  0  2  0  0  0  0  0  0  0]]
acc        0.3088235294117647
ari        0.08055270806422098
nmi        0.1803714562166085


Lo

 15%|█████████████████████████████▎                                                                                                                                                                     | 3/20 [00:28<02:38,  9.32s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.07585366 0.02226284 0.06412125]
            [0.79838903 0.83238679 0.48255671]
            [0.28396161 0.08689762 0.34104079]]
confusion  [[27 16  3  0  3  1 13  0 12  6  0  0  0]
            [ 9 12  3 32  1  5  0  0 13  8  0  0  0]
            [ 7 11 17 41  9  7  0  1 17 13  0  1  0]
            [12  3  0 32 32 12 10  0 10  5  0  5  0]
            [26 17 10  8 51 30  3  6 12  1  0  1  0]
            [ 3 10  6 12  9 22  0  3  5  1  0  1  0]
            [ 1  1  0  0  3  0 10  0  2  0  0  0  0]
            [ 2  1  1  0  0  1  0  1  0  0  0  0  0]
            [ 0  1  0  0  1  0  1  0  6  0  0  0  0]
            [10  1  0  1  3  0  8  0 13  8  0  0  0]
            [ 1  1  0  0  6  0 10  0  0  1  0  0  0]
            [ 0  0  2  0  0  0  0  0  2  0  0  0  0]
            [ 1  1  0  0  0  0  0  0  1  0  0  0  0]]
acc        0.24866310160427807
ari        0.07454022253241312
nmi        0.17659754650399107




 20%|███████████████████████████████████████                                                                                                                                                            | 4/20 [00:37<02:27,  9.20s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.09914459 0.03547062 0.08532761]
            [0.85009517 0.89306562 0.56040794]
            [0.33619752 0.10521543 0.36882008]]
confusion  [[33  3 19  0  0  0  0  1  0  3 22  0  0]
            [18 10 41 11  0  0  0  2  0  1  0  0  0]
            [23  8 52 17  5  5  6  3  4  1  0  0  0]
            [ 2  8 19 26 26  8  8  2  6  3 13  0  0]
            [28 36 15  9 44 13 10  5  0  0  5  0  0]
            [12  8 16  3  7 13  9  4  0  0  0  0  0]
            [ 0  1  2  0  0  0  0  0  0  0 14  0  0]
            [ 4  2  0  0  0  0  0  0  0  0  0  0  0]
            [ 1  1  6  0  1  0  0  0  0  0  0  0  0]
            [ 5  0 21  0  0  0  0  0  1 10  7  0  0]
            [ 0  0  2  0  0  0  0  0  0  0 17  0  0]
            [ 2  0  2  0  0  0  0  0  0  0  0  0  0]
            [ 2  0  1  0  0  0  0  0  0  0  0  0  0]]
acc        0.27406417112299464
ari        0.06688754546781607
nmi        0.2082419749054755


L

 25%|████████████████████████████████████████████████▊                                                                                                                                                  | 5/20 [00:46<02:16,  9.11s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.11214063 0.04727166 0.1025326 ]
            [0.85315747 0.89555995 0.63058603]
            [0.36141653 0.15731018 0.40414384]]
confusion  [[54  3 11  0  0  2  0  3  0  5  2  1  0]
            [ 3 25 33  0  0 11  0 11  0  0  0  0  0]
            [ 7  8 48 21  1  4  1 20  0 10  4  0  0]
            [16  0  6 58  8  0  2  0  6 14 10  1  0]
            [10  7 10  1 56 48  0 26  1  4  1  1  0]
            [ 0  4 15  0 24 25  0  3  0  0  0  1  0]
            [11  0  0  0  0  0  0  0  0  2  4  0  0]
            [ 3  0  0  0  0  1  0  2  0  0  0  0  0]
            [ 0  0  6  1  0  0  0  0  1  0  1  0  0]
            [18  0  2  0  0  0  0  0  0 20  4  0  0]
            [ 9  0  0  1  0  0  0  0  0  0  9  0  0]
            [ 1  1  2  0  0  0  0  0  0  0  0  0  0]
            [ 0  0  1  0  0  0  0  2  0  0  0  0  0]]
acc        0.3983957219251337
ari        0.17476514527925696
nmi        0.3224866992738384


Lo

 30%|██████████████████████████████████████████████████████████▌                                                                                                                                        | 6/20 [00:55<02:06,  9.06s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.12155613 0.05352817 0.10955789]
            [0.86819707 0.9032739  0.71484317]
            [0.39269695 0.16052111 0.42621283]]
confusion  [[57  2 10  0  1  0  0  4  0  7  0  0  0]
            [ 4 24 34  1  8  0  0 12  0  0  0  0  0]
            [ 6  4 52 24  4  0  0 23  0  6  5  0  0]
            [ 6  0  9 68  0  0  9  6  0  9  8  6  0]
            [11  9 10  2 47 49  0 32  0  5  0  0  0]
            [ 0  8 16  0 17 24  0  7  0  0  0  0  0]
            [11  0  0  0  0  0  1  0  0  2  3  0  0]
            [ 2  1  0  0  2  0  0  1  0  0  0  0  0]
            [ 1  0  6  1  0  0  0  1  0  0  0  0  0]
            [21  0  0  0  0  0  0  0  0 20  3  0  0]
            [ 8  0  0  0  0  0  0  0  1  0 10  0  0]
            [ 1  1  2  0  0  0  0  0  0  0  0  0  0]
            [ 0  1  1  0  0  0  0  1  0  0  0  0  0]]
acc        0.40641711229946526
ari        0.19274099396842306
nmi        0.3462119988199815


L

 35%|████████████████████████████████████████████████████████████████████▎                                                                                                                              | 7/20 [01:04<01:57,  9.05s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.13131723 0.06835438 0.11442381]
            [0.88105271 0.86857404 0.71821838]
            [0.42164992 0.19627601 0.44051236]]
confusion  [[57  4  5  0  1  0  0  4  0 10  0  0  0]
            [ 4 23 33  1  8  0  0 12  0  2  0  0  0]
            [ 6  2 39 35  3  1  1 26  0  9  2  0  0]
            [ 2  0  4 82  0  0 12  6  3  9  2  1  0]
            [12  7  6  4 46 51  0 34  0  5  0  0  0]
            [ 0  5 16  0 15 26  0 10  0  0  0  0  0]
            [10  0  0  0  0  0  1  0  0  2  4  0  0]
            [ 1  1  0  0  1  0  0  2  0  0  0  1  0]
            [ 1  0  1  0  0  0  0  0  1  5  1  0  0]
            [22  0  0  0  0  0  0  0  0 19  3  0  0]
            [ 4  0  0  2  0  0  0  0  0  0 13  0  0]
            [ 1  1  2  0  0  0  0  0  0  0  0  0  0]
            [ 0  1  0  0  0  0  0  1  0  1  0  0  0]]
acc        0.41310160427807485
ari        0.22631106168810494
nmi        0.3669440751456299


L

 40%|██████████████████████████████████████████████████████████████████████████████                                                                                                                     | 8/20 [01:13<01:48,  9.02s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.13614489 0.08019879 0.12581258]
            [0.87398804 0.9160953  0.78830395]
            [0.44858178 0.25270416 0.47741602]]
confusion  [[52  5  9  0  0  1  1  5  0  8  0  0  0]
            [ 1 22 37  0  0 10  0 13  0  0  0  0  0]
            [ 2  9 46 38  1  3  1 22  1  1  0  0  0]
            [ 0  0  5 84  0  0 14  5  3  8  2  0  0]
            [10 12  8  2 52 46  0 31  0  4  0  0  0]
            [ 0  7 15  0 25 20  0  5  0  0  0  0  0]
            [ 1  0  0  0  0  0  9  0  0  2  5  0  0]
            [ 0  3  0  0  0  3  0  0  0  0  0  0  0]
            [ 1  0  4  0  0  0  0  0  1  2  1  0  0]
            [17  1  0  0  0  0  0  0  0 22  4  0  0]
            [ 0  0  0  1  0  0  2  0  0  0 16  0  0]
            [ 1  1  2  0  0  0  0  0  0  0  0  0  0]
            [ 0  1  1  0  0  1  0  0  0  0  0  0  0]]
acc        0.43315508021390375
ari        0.24520863030426635
nmi        0.400041277516666


 45%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 9/20 [01:22<01:38,  8.95s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.14668831 0.07239929 0.13163399]
            [0.89533449 0.90994053 0.73342919]
            [0.46780086 0.23195274 0.49988943]]
confusion  [[49  6  0  0  0  1  5  0  0 17  1  2  0]
            [ 0 29  0  0  2  8  0  0  0 34  5  5  0]
            [ 0  4 27 12  1  4  0  0  0 45 13 18  0]
            [ 0  0 38 45  2  0  0  0  0 12 24  0  0]
            [ 8 13  0  0 61 37  0  0  0 12 19 15  0]
            [ 0  7  0  1 29 14  0  0  0 15  5  1  0]
            [ 1  0  0  0  0  0 12  0  0  3  1  0  0]
            [ 0  3  0  0  0  3  0  0  0  0  0  0  0]
            [ 0  0  0  1  0  0  0  0  0  7  1  0  0]
            [19  0  0  0  0  0  3  0  0 22  0  0  0]
            [ 0  0  1  9  0  0  7  0  0  0  2  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  0  1  0  0  0  1  0  0  0]]
acc        0.34893048128342247
ari        0.1701466868514027
nmi        0.3535785313609826


Lo

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 10/20 [01:30<01:29,  8.93s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.15411077 0.08991332 0.13748998]
            [0.90565483 0.92572276 0.78446323]
            [0.49442383 0.28075007 0.51970883]]
confusion  [[46  6 16  0  0  1  9  0  1  0  0  2  0]
            [ 1 30 35  0  1  3  0  0  7  0  0  6  0]
            [ 0  5 44 28  0  2  0  0 18  0 12 15  0]
            [ 0  0 12 44  0  0  0  0 26  0 39  0  0]
            [10 18 12  1 59 29  1  0 18  0  2 15  0]
            [ 0 10 15  1 30  7  0  0  4  0  1  4  0]
            [ 0  0  2  0  0  0 14  0  1  0  0  0  0]
            [ 0  4  0  0  0  2  0  0  0  0  0  0  0]
            [ 1  0  6  0  0  0  1  0  1  0  0  0  0]
            [22  0 19  0  0  0  3  0  0  0  0  0  0]
            [ 0  0  0  1  0  0 10  0  3  0  5  0  0]
            [ 1  1  2  0  0  0  0  0  0  0  0  0  0]
            [ 0  2  1  0  0  0  0  0  0  0  0  0  0]]
acc        0.3342245989304813
ari        0.16403354413115248
nmi        0.34631277792718007


L

 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                       | 11/20 [01:39<01:20,  8.92s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.16142814 0.09180092 0.14590631]
            [0.91346639 0.91455379 0.82941167]
            [0.50452701 0.2605796  0.53860025]]
confusion  [[53  6  3  0  0  1  3  3  0 11  1  0  0]
            [ 2 29 35  0  0  5  2  9  0  1  0  0  0]
            [ 4  5 43 40  1  4 14  8  0  3  2  0  0]
            [ 0  0  3 84  0  0 21  0  0  9  4  0  0]
            [14 12  7  0 52 47  0 30  0  3  0  0  0]
            [ 0  7 16  1 23 19  0  6  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  2  6  0  0]
            [ 0  2  0  0  0  4  0  0  0  0  0  0  0]
            [ 1  0  2  0  0  0  1  0  0  4  1  0  0]
            [17  0  0  0  0  0  2  0  0 18  7  0  0]
            [ 0  0  0  0  0  0  2  0  0  0 17  0  0]
            [ 1  1  2  0  0  0  0  0  0  0  0  0  0]
            [ 0  2  0  0  0  1  0  0  0  0  0  0  0]]
acc        0.43315508021390375
ari        0.25623735840964484
nmi        0.40399800836109895




 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                             | 12/20 [01:48<01:11,  8.93s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.16961556 0.10278283 0.1552163 ]
            [0.9234116  0.93394655 0.86190057]
            [0.53030791 0.31098604 0.56387392]]
confusion  [[54  4  2  0  0  2  2  2  0 13  2  0  0]
            [ 2 27 32  1  1  8  1  9  0  2  0  0  0]
            [ 3  7 40 43  2  4 14  7  0  3  1  0  0]
            [ 0  0  1 86  0  0 20  0  0 10  4  0  0]
            [15 10  5  0 60 41  0 30  0  4  0  0  0]
            [ 0  7 16  1 30 14  0  4  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  2  6  0  0]
            [ 0  2  0  0  0  4  0  0  0  0  0  0  0]
            [ 1  0  0  0  0  0  1  0  0  6  1  0  0]
            [12  0  0  0  0  0  2  0  0 19 11  0  0]
            [ 0  0  0  0  0  0  4  0  0  0 15  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  0  1  0  0  0  1  0  0  0]]
acc        0.43315508021390375
ari        0.2672276188758469
nmi        0.4084979159638208


Lo

 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 13/20 [01:57<01:02,  8.92s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.17920866 0.10961076 0.16220246]
            [0.9268121  0.93561797 0.8692301 ]
            [0.5532466  0.33567898 0.57746031]]
confusion  [[52  6  1  0  1  0  5  2  0 12  2  0  0]
            [ 1 32 33  1  2  0  2 11  0  1  0  0  0]
            [ 4  7 45 42  4  1 11  9  0  0  1  0  0]
            [ 0  0  2 86  0  0 20  0  0  9  4  0  0]
            [14 13  7  0 39 58  0 31  0  3  0  0  0]
            [ 0 10 15  1  9 31  0  6  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1  7  0  0]
            [ 0  2  0  0  4  0  0  0  0  0  0  0  0]
            [ 1  0  0  0  0  0  1  0  0  6  1  0  0]
            [14  0  0  0  0  0  2  0  0 19  9  0  0]
            [ 0  0  0  1  0  0  4  0  0  0 14  0  0]
            [ 1  1  2  0  0  0  0  0  0  0  0  0  0]
            [ 0  1  0  0  1  0  0  0  0  1  0  0  0]]
acc        0.43716577540106955
ari        0.26713227607940004
nmi        0.4151908291007856


L

 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 14/20 [02:06<00:53,  8.97s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.18774096 0.11614148 0.17079843]
            [0.9277466  0.90823485 0.87554307]
            [0.57114733 0.34704203 0.60068994]]
confusion  [[56  5  1  0  0  3  2  1  0 10  3  0  0]
            [ 1 25 30  0  1  8  1 11  0  5  1  0  0]
            [ 3  7 37 43  1  4 11  9  0  7  2  0  0]
            [ 0  0  0 86  0  0 20  0  0 11  4  0  0]
            [16 11  3  1 58 42  0 31  0  3  0  0  0]
            [ 0  7 15  1 28 15  0  6  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1  7  0  0]
            [ 0  2  0  0  0  4  0  0  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0  6  2  0  0]
            [12  0  0  0  0  0  2  0  0 18 12  0  0]
            [ 0  0  0  0  0  0  4  0  0  0 15  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  0  2  0  0  0  0  0  0  0]]
acc        0.4264705882352941
ari        0.26465818424703086
nmi        0.4071845616687302


Lo

 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                | 15/20 [02:15<00:44,  8.97s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.19527556 0.12304025 0.18023783]
            [0.92849202 0.92857944 0.89381197]
            [0.59090309 0.36299292 0.61480275]]
confusion  [[51  5  1  0  3  0  5  2  0 11  3  0  0]
            [ 1 25 32  0  9  0  3  9  0  3  1  0  0]
            [ 2  7 42 44  4  1 18  3  0  2  1  0  0]
            [ 0  0  1 87  0  0 20  0  0 10  3  0  0]
            [14 15  4  0 40 59  2 29  0  2  0  0  0]
            [ 0  7 15  1 12 32  0  5  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  2  6  0  0]
            [ 0  2  0  0  4  0  0  0  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0  7  1  0  0]
            [ 9  0  0  0  0  0  3  0  0 18 14  0  0]
            [ 0  0  0  1  0  0  4  0  0  0 14  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  0  1  0  2  0  0  0  0  0  0  0  0]]
acc        0.42513368983957217
ari        0.26707955033452635
nmi        0.4093113994363087


L

 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 16/20 [02:24<00:35,  8.96s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.2036987  0.1334852  0.18762201]
            [0.93396661 0.94381744 0.89760863]
            [0.60617975 0.38642431 0.63290976]]
confusion  [[56  5  1  0  0  3  3  1  0 10  2  0  0]
            [ 1 23 31  0  0 10  1 12  0  5  0  0  0]
            [ 3  9 41 41  1  3 14  8  0  4  0  0  0]
            [ 0  0  0 84  0  0 20  0  0 12  5  0  0]
            [16 17  2  0 60 39  0 31  0  0  0  0  0]
            [ 0  7 15  0 33 12  0  5  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1  7  0  0]
            [ 0  2  0  0  0  4  0  0  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0  6  2  0  0]
            [10  0  0  0  0  0  2  0  0 18 14  0  0]
            [ 0  0  0  1  0  0  4  0  0  0 14  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  0  2  0  0  0  0  0  0  0]]
acc        0.42379679144385024
ari        0.26993572359948625
nmi        0.4261627394628912


L

 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 17/20 [02:33<00:26,  8.94s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.21139363 0.13868379 0.19712827]
            [0.9365954  0.94534612 0.9058532 ]
            [0.6201324  0.40134075 0.64683664]]
confusion  [[54  6  0  0  0  3  4  1  0 10  3  0  0]
            [ 1 23 32  0  0 11  2 11  0  3  0  0  0]
            [ 2  7 44 42  2  4 16  6  0  1  0  0  0]
            [ 0  0  1 86  0  0 21  0  0 10  3  0  0]
            [15 18  3  0 60 39  0 30  0  0  0  0  0]
            [ 0  7 15  0 33 12  0  5  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1  7  0  0]
            [ 0  2  0  0  0  4  0  0  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0  7  1  0  0]
            [10  0  0  0  0  0  2  0  0 17 15  0  0]
            [ 0  0  0  1  0  0  5  0  0  0 13  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  0  2  0  0  0  0  0  0  0]]
acc        0.42513368983957217
ari        0.2739247070780687
nmi        0.42943430510867414


L

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 18/20 [02:42<00:17,  8.88s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.21800428 0.1405402  0.20224201]
            [0.9402069  0.94858322 0.89824212]
            [0.63117943 0.40075048 0.66038918]]
confusion  [[57  6  0  0  0  2  2  2  0 10  2  0  0]
            [ 0 26 32  0  0  9  1 11  0  3  1  0  0]
            [ 3  9 43 42  1  3 15  6  0  2  0  0  0]
            [ 0  0  0 83  0  0 21  0  0 12  5  0  0]
            [18 16  1  0 60 38  0 32  0  0  0  0  0]
            [ 0  7 15  0 33 12  0  5  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1  7  0  0]
            [ 0  2  0  0  0  4  0  0  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0  6  2  0  0]
            [10  0  0  0  0  0  2  0  0 19 13  0  0]
            [ 0  0  0  1  0  0  5  0  0  0 13  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  0  2  0  0  0  0  0  0  0]]
acc        0.4304812834224599
ari        0.27566026434548385
nmi        0.4370089957193056


Lo

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 19/20 [02:51<00:08,  8.85s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.23070754 0.14467952 0.20941289]
            [0.92955916 0.93929782 0.89811698]
            [0.64721939 0.41336107 0.66931855]]
confusion  [[55  6  0  0  2  0  2  3  0 11  2  0  0]
            [ 1 28 32  0  5  0  2 11  0  3  1  0  0]
            [ 1  8 44 42  3  2 18  5  0  1  0  0  0]
            [ 0  0  2 83  0  0 22  0  0 10  4  0  0]
            [15 19  1  0 40 58  0 32  0  0  0  0  0]
            [ 0  7 15  0 12 33  0  5  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1  7  0  0]
            [ 0  2  0  0  4  0  0  0  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0  7  1  0  0]
            [10  0  0  0  0  0  2  0  0 19 13  0  0]
            [ 0  0  0  0  0  0  6  0  0  0 13  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  2  0  0  0  0  0  0  0  0]]
acc        0.43315508021390375
ari        0.2755903868470041
nmi        0.43760929326161446


L

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [03:00<00:00,  9.00s/it]




Metrics    Value
---------  ------------------------------------------
r2         [[0.23371273 0.16326781 0.2111633 ]
            [0.9213446  0.94201426 0.88849843]
            [0.65070852 0.45468791 0.66881152]]
confusion  [[56  6  0  0  4  0  1  1  0 11  2  0  0]
            [ 0 21 32  0 14  0  1 10  0  4  1  0  0]
            [ 2 12 43 42  4  1 15  4  0  1  0  0  0]
            [ 0  0  1 84  0  0 20  0  0 11  5  0  0]
            [14 19  2  0 41 59  1 29  0  0  0  0  0]
            [ 0  7 15  0 13 32  0  5  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  2  6  0  0]
            [ 0  2  0  0  4  0  0  0  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0  8  0  0  0]
            [10  0  0  0  0  0  2  0  0 19 13  0  0]
            [ 0  0  0  1  0  0  4  0  0  0 14  0  0]
            [ 1  1  0  0  0  0  0  0  0  2  0  0  0]
            [ 0  1  0  0  2  0  0  0  0  0  0  0  0]]
acc        0.4264705882352941
ari        0.2713976009865024
nmi        0.43150122490882
finetun

  0%|                                                                                                                                                                                                           | 0/20 [00:00<?, ?it/s]



Losses                         Value
------------------------  ----------
ddc_loss_head_8            0.103822
ddc_loss_head_4            0.10669
self_entropy_loss_head_3  -0.0176318
ddc_loss_head_2            0.105366
ddc_loss_head_3            0.107135
self_entropy_loss_head_0  -0.0181436
ddc_loss_head_5            0.107341
ddc_loss_head_1            0.106522
self_entropy_loss_head_4  -0.01793
ddc_loss_head_0            0.105473
self_entropy_loss_head_9  -0.0164872
ddc_loss_head_7            0.105667
self_entropy_loss_head_6  -0.0174658
ddc_loss_head_6            0.106435
self_entropy_loss_head_5  -0.0175344
reconstruction_loss        0.39266
self_entropy_loss_head_2  -0.0176742
self_entropy_loss_head_8  -0.0182058
self_entropy_loss_head_1  -0.017336
ddc_loss_head_9            0.109137
self_entropy_loss_head_7  -0.0167261
best_head                  7
best model saved at ../saved_results/dlpfc/finetune_best.pt 



  5%|█████████▊                                                                                                                                                                                         | 1/20 [00:12<03:49, 12.09s/it]



Metrics    Value
---------  -------------------------------------------------------
r2         [[0.20794369 0.14250872 0.19030106]
            [0.89557556 0.94573373 0.78209211]
            [0.61384457 0.40902442 0.66834155]]
confusion  [[ 65   8   0   0   0   5   4   1   0  15   3   0   0]
            [  0  27  39   0   0  14   4  15   0   4   1   0   0]
            [  1  13  51  57   2   3  20   5   0   3   0   0   0]
            [  0   0   0 102   0   0  26   0   0  16   7   0   0]
            [ 17  30   1   0  70  47   0  42   0   0   0   0   0]
            [  0   8  18   0  35  20   0   9   0   0   0   0   0]
            [  0   0   0   0   0   0   9   0   0   4   8   0   0]
            [  0   2   0   0   0   4   0   1   0   0   0   0   0]
            [  0   0   0   0   0   0   1   0   0  11   0   0   0]
            [  9   0   0   0   0   0   3   0   0  23  20   0   0]
            [  0   0   0   1   0   0   7   0   0   0  15   0   0]
            [  1   2   1   0   0   0   0   0  

 10%|███████████████████▌                                                                                                                                                                               | 2/20 [00:24<03:38, 12.14s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.2239208  0.14905873 0.19894342]
            [0.91423217 0.95200916 0.83372465]
            [0.64657375 0.41943921 0.68004284]]
confusion  [[63  7  0  0  0  6  2  1  0 16  6  0  0]
            [ 0 28 40  0  0 13  1 16  0  4  2  0  0]
            [ 2  8 52 57  3  4 20  6  0  3  0  0  0]
            [ 0  0  0 96  0  0 29  0  0 16 10  0  0]
            [17 28  1  0 73 44  0 44  0  0  0  0  0]
            [ 0  8 18  0 38 17  0  9  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  4  8  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0 11  0  0  0]
            [ 9  0  0  0  0  0  2  0  0 23 21  0  0]
            [ 0  0  0  0  0  0  8  0  0  0 15  0  0]
            [ 1  2  0  0  0  0  0  0  0  3  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.4027777777777778
ari        0.2573392990762731
nmi        0.4261419152064543


Los

 15%|█████████████████████████████▎                                                                                                                                                                     | 3/20 [00:36<03:25, 12.06s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.23621043 0.14972975 0.20992655]
            [0.93081673 0.93013399 0.83923229]
            [0.6701305  0.41317326 0.69596705]]
confusion  [[66  7  0  0  0  7  2  1  0 15  3  0  0]
            [ 0 26 39  0  0 15  2 17  0  4  1  0  0]
            [ 2 12 50 56  2  3 22  5  0  3  0  0  0]
            [ 0  0  0 97  0  0 28  0  0 15 11  0  0]
            [19 25  1  0 71 49  0 42  0  0  0  0  0]
            [ 0  8 18  0 35 19  0 10  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  2 10  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0 11  0  0  0]
            [10  0  0  0  0  0  1  0  0 22 22  0  0]
            [ 0  0  0  1  0  0  7  0  0  0 15  0  0]
            [ 2  1  0  0  0  0  0  0  0  3  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.4017094017094017
ari        0.2571930262569915
nmi        0.4272119588801568


Los

 20%|███████████████████████████████████████                                                                                                                                                            | 4/20 [00:48<03:11, 11.98s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.24530404 0.15957677 0.2180912 ]
            [0.93767979 0.9473343  0.87855236]
            [0.68568899 0.43844086 0.70408087]]
confusion  [[65  7  0  0  0  5  3  1  0 15  5  0  0]
            [ 1 24 39  0  0 15  3 16  0  5  1  0  0]
            [ 2 12 48 58  1  3 24  4  0  3  0  0  0]
            [ 0  0  0 99  0  0 27  0  0 14 11  0  0]
            [18 25  1  0 71 49  1 42  0  0  0  0  0]
            [ 0  8 18  0 35 19  0 10  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1 11  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  2  0  0 10  0  0  0]
            [ 9  0  0  0  0  0  2  0  0 21 23  0  0]
            [ 0  0  0  1  0  0  7  0  0  0 15  0  0]
            [ 1  2  0  0  0  0  0  0  0  3  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.3974358974358974
ari        0.25811608489961474
nmi        0.42250500787891876


 25%|████████████████████████████████████████████████▊                                                                                                                                                  | 5/20 [01:00<02:59, 11.98s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.25237059 0.16625698 0.22899693]
            [0.93732645 0.94240853 0.88161846]
            [0.68968962 0.45882664 0.72009451]]
confusion  [[60  7  0  0  0  7  3  2 15  7  0  0  0]
            [ 0 24 39  0  0 17  2 18  3  1  0  0  0]
            [ 1 14 51 58  0  2 23  5  1  0  0  0  0]
            [ 0  0  1 95  0  0 30  0 12 13  0  0  0]
            [18 25  1  0 69 50  0 44  0  0  0  0  0]
            [ 0  7 18  0 34 21  0 10  0  0  0  0  0]
            [ 0  0  0  0  0  0  7  0  2 12  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  2  0 10  0  0  0  0]
            [ 9  0  1  0  0  0  2  0 19 24  0  0  0]
            [ 0  0  0  1  0  0  7  0  0 15  0  0  0]
            [ 1  2  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.38675213675213677
ari        0.2504083676063028
nmi        0.4226006946709055


Lo

 30%|██████████████████████████████████████████████████████████▌                                                                                                                                        | 6/20 [01:11<02:46, 11.93s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.25818234 0.1686953  0.23514553]
            [0.93507989 0.95208717 0.88874664]
            [0.69506617 0.45937314 0.72155316]]
confusion  [[63  7  0  0  0  7  2  1 15  6  0  0  0]
            [ 2 21 39  0  0 19  3 15  4  1  0  0  0]
            [ 2  9 51 60  0  4 21  5  1  2  0  0  0]
            [ 0  0  0 96  0  0 26  0 13 16  0  0  0]
            [19 22  2  0 70 51  0 43  0  0  0  0  0]
            [ 0  7 18  0 34 21  0 10  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  3  9  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [ 6  0  0  0  0  0  2  0 20 27  0  0  0]
            [ 0  0  0  1  0  0  7  0  0 15  0  0  0]
            [ 2  1  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.3952991452991453
ari        0.25394796156740934
nmi        0.4206511660116455


 35%|████████████████████████████████████████████████████████████████████▎                                                                                                                              | 7/20 [01:23<02:35, 11.95s/it]



Metrics    Value
---------  -------------------------------------------------------
r2         [[0.27130494 0.18039206 0.24431583]
            [0.9366838  0.95305244 0.89231272]
            [0.70958647 0.47673398 0.73621689]]
confusion  [[ 64   6   0   0   0   7   3   2  15   4   0   0   0]
            [  0  23  39   0   0  19   2  17   3   1   0   0   0]
            [  0  15  46  60   0   4  23   5   2   0   0   0   0]
            [  0   0   1 100   0   0  25   0  13  12   0   0   0]
            [ 18  24   1   0  71  49   0  44   0   0   0   0   0]
            [  0   7  18   0  34  21   0  10   0   0   0   0   0]
            [  0   0   0   0   0   0   9   0   1  11   0   0   0]
            [  0   2   0   0   0   4   0   1   0   0   0   0   0]
            [  0   0   0   0   0   0   1   0  11   0   0   0   0]
            [  9   0   1   0   0   0   2   0  19  24   0   0   0]
            [  0   0   0   1   0   0   7   0   0  15   0   0   0]
            [  1   2   0   0   0   0   0   0  

 40%|██████████████████████████████████████████████████████████████████████████████                                                                                                                     | 8/20 [01:35<02:23, 11.97s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.27870764 0.19224035 0.25187356]
            [0.94439775 0.95938896 0.90740133]
            [0.7144922  0.50485278 0.74572227]]
confusion  [[63  7  0  0  0  8  3  2 14  4  0  0  0]
            [ 1 24 39  0  0 18  2 16  3  1  0  0  0]
            [ 0 13 48 61  0  4 23  5  1  0  0  0  0]
            [ 0  0  1 98  0  0 26  0 13 13  0  0  0]
            [18 24  1  0 70 50  0 44  0  0  0  0  0]
            [ 0  7 18  0 35 19  0 11  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  5  7  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [ 8  0  0  0  0  0  2  0 20 25  0  0  0]
            [ 0  0  0  1  0  0  7  0  0 15  0  0  0]
            [ 1  2  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.39316239316239315
ari        0.2570835697453772
nmi        0.4263967773286348


Lo

 45%|███████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 9/20 [01:47<02:11, 11.99s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.29156392 0.20592069 0.26472906]
            [0.94414491 0.96063445 0.91676144]
            [0.72563198 0.52294042 0.75025834]]
confusion  [[66  8  0  0  0  5  3  2 13  4  0  0  0]
            [ 1 25 38  0  0 18  2 16  3  1  0  0  0]
            [ 0 18 43 62  0  4 22  5  1  0  0  0  0]
            [ 0  0  1 99  0  0 25  0 14 12  0  0  0]
            [18 24  1  0 70 49  0 45  0  0  0  0  0]
            [ 0  7 18  0 34 20  0 11  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  1 11  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [10  0  0  0  0  0  2  0 20 23  0  0  0]
            [ 0  0  0  2  0  0  7  0  0 14  0  0  0]
            [ 1  2  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.3920940170940171
ari        0.25793431314370935
nmi        0.4271456928105201


Lo

 50%|█████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                 | 10/20 [02:00<02:00, 12.07s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.3045768  0.20924471 0.27508673]
            [0.94281378 0.94983466 0.91155635]
            [0.73823272 0.52752252 0.75150643]]
confusion  [[66  8  0  0  0  6  3  2 13  3  0  0  0]
            [ 1 23 39  0  0 19  4 14  3  1  0  0  0]
            [ 0 15 46 61  0  4 24  4  1  0  0  0  0]
            [ 0  0  1 99  0  0 25  0 14 12  0  0  0]
            [18 24  1  0 69 52  0 43  0  0  0  0  0]
            [ 0  7 18  0 33 22  0 10  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  1 11  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [10  0  0  0  0  0  2  0 20 23  0  0  0]
            [ 0  0  0  2  0  0  7  0  0 14  0  0  0]
            [ 1  2  1  0  0  0  0  0  2  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.3942307692307692
ari        0.2580191749384057
nmi        0.4260622587782607


Los

 55%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                                       | 11/20 [02:12<01:48, 12.01s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.31997166 0.23134497 0.29048604]
            [0.9502324  0.96259878 0.92761463]
            [0.75371893 0.57089498 0.77321964]]
confusion  [[63  9  0  0  0  6  3  1 11  8  0  0  0]
            [ 2 25 39  0  0 17  2 15  3  1  0  0  0]
            [ 1 18 45 58  0  4 24  4  1  0  0  0  0]
            [ 0  0  1 98  0  0 25  0 13 14  0  0  0]
            [18 24  1  0 68 52  0 44  0  0  0  0  0]
            [ 0  8 18  0 33 21  0 10  0  0  0  0  0]
            [ 0  0  0  0  0  0  8  0  1 12  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [ 9  0  1  0  0  0  2  0 19 24  0  0  0]
            [ 0  0  0  2  0  0  7  0  0 14  0  0  0]
            [ 1  2  1  0  0  0  0  0  2  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.3888888888888889
ari        0.2504065247213066
nmi        0.417446101514948


Loss

 60%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                             | 12/20 [02:24<01:35, 12.00s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.32696315 0.22298319 0.29653913]
            [0.9529012  0.9598729  0.92556923]
            [0.76028556 0.55210541 0.77794152]]
confusion  [[62  9  0  0  0  6  4  1 13  6  0  0  0]
            [ 1 25 39  0  0 17  2 16  3  1  0  0  0]
            [ 0 18 45 58  0  4 24  5  1  0  0  0  0]
            [ 0  0  1 98  0  0 25  0 14 13  0  0  0]
            [18 24  1  0 69 50  0 45  0  0  0  0  0]
            [ 0  8 18  0 32 21  0 11  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  1 11  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [ 9  0  1  0  0  0  2  0 19 24  0  0  0]
            [ 0  0  0  2  0  0  7  0  0 14  0  0  0]
            [ 1  2  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.38995726495726496
ari        0.25030873413714544
nmi        0.4200240437389193


 65%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                    | 13/20 [02:35<01:23, 11.86s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.33717076 0.24143965 0.30638922]
            [0.95423429 0.95797946 0.92580282]
            [0.75978279 0.57726625 0.78086448]]
confusion  [[68  9  0  0  0  4  3  1  0 13  3  0  0]
            [ 1 26 39  0  0 15  0 20  0  3  0  0  0]
            [ 1 20 42 56  0  4 26  4  0  2  0  0  0]
            [ 0  0  1 96  0  0 27  0  0 14 13  0  0]
            [19 23  1  0 68 51  0 45  0  0  0  0  0]
            [ 0  7 18  0 32 22  0 11  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  0  1 11  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0  0 11  0  0  0]
            [11  0  0  0  0  0  2  0  0 20 22  0  0]
            [ 0  0  0  2  0  0  7  0  0  0 14  0  0]
            [ 1  2  0  0  0  0  0  0  0  3  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.391025641025641
ari        0.25377468383708457
nmi        0.42943610985480307


 70%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 14/20 [02:47<01:11, 11.87s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.34522271 0.22805518 0.31654672]
            [0.95490717 0.95723517 0.93011169]
            [0.7719974  0.57150397 0.78461163]]
confusion  [[65  9  0  0  0  6  3  1 13  4  0  0  0]
            [ 2 24 39  0  0 17  1 17  3  1  0  0  0]
            [ 1 16 46 56  0  4 26  4  2  0  0  0  0]
            [ 0  0  1 98  0  0 26  0 13 13  0  0  0]
            [18 24  0  0 67 54  0 44  0  0  0  0  0]
            [ 0  7 18  0 29 25  0 11  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  1 11  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [ 9  0  0  0  0  0  2  0 20 24  0  0  0]
            [ 0  0  0  2  0  0  7  0  0 14  0  0  0]
            [ 1  2  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.3952991452991453
ari        0.2538109576246851
nmi        0.4254918351974784


 75%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                | 15/20 [02:59<00:59, 11.90s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.35773393 0.25647288 0.32390199]
            [0.9501891  0.95697657 0.92388181]
            [0.76918391 0.59360134 0.78710151]]
confusion  [[63  9  0  0  0  6  3  1 13  6  0  0  0]
            [ 0 24 39  0  0 18  0 20  3  0  0  0  0]
            [ 0 17 45 59  0  4 24  5  1  0  0  0  0]
            [ 0  0  2 98  0  0 25  0 11 15  0  0  0]
            [18 24  0  0 68 53  0 44  0  0  0  0  0]
            [ 0  8 18  0 32 21  0 11  0  0  0  0  0]
            [ 0  0  0  0  0  0  9  0  2 10  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [ 8  0  1  0  0  0  2  0 19 25  0  0  0]
            [ 0  0  0  2  0  0  7  0  0 14  0  0  0]
            [ 1  2  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.38995726495726496
ari        0.25368012305380255
nmi        0.42896854824560265




 80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 16/20 [03:11<00:47, 11.92s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.36860757 0.2644434  0.33696073]
            [0.95335709 0.95925341 0.92918332]
            [0.77755089 0.60451733 0.79376916]]
confusion  [[65  8  0  0  0  6  3  2 14  3  0  0  0]
            [ 3 24 39  0  0 17  0 18  3  0  0  0  0]
            [ 1 18 45 56  0  3 25  5  2  0  0  0  0]
            [ 0  1  1 98  0  0 26  0 13 12  0  0  0]
            [18 24  1  0 68 52  0 44  0  0  0  0  0]
            [ 0  7 18  0 32 22  0 11  0  0  0  0  0]
            [ 0  0  0  0  0  0 11  0  2  8  0  0  0]
            [ 0  2  0  0  0  4  0  1  0  0  0  0  0]
            [ 0  0  0  0  0  0  1  0 11  0  0  0  0]
            [10  0  1  0  0  0  2  0 19 23  0  0  0]
            [ 0  0  0  2  0  0  7  0  0 14  0  0  0]
            [ 1  2  0  0  0  0  0  0  3  0  0  0  0]
            [ 0  1  0  0  0  2  0  1  0  0  0  0  0]]
acc        0.39316239316239315
ari        0.25170614791564433
nmi        0.42022392974622524




 85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 17/20 [03:23<00:35, 11.92s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.37653958 0.28241376 0.34079594]
            [0.95677382 0.95976253 0.93117894]
            [0.78304731 0.62962003 0.79695707]]
confusion  [[41  0  0  0  0  7  0  4 11 32  1  5  0]
            [ 5 37  0  0  1 19  0 24  3  0  3  3  9]
            [ 0 17 36 29  0  6  0 13  1  0 19 32  2]
            [ 8  3 45 56  0  0  0  1  9  3 22  1  3]
            [16  0  0  2 67 50  0 16  0  1  4 17 34]
            [ 0 18  0  2 30 22  0  7  0  0  3  1  7]
            [ 1  1  0  0  0  0  0  0  5  8  6  0  0]
            [ 0  0  0  0  0  4  0  2  0  0  0  0  1]
            [ 1  3  0  0  0  0  0  0  6  1  1  0  0]
            [ 4  0  0  0  0  0  0  0 24 27  0  0  0]
            [ 6  0  0  6  0  0  0  0  0  4  7  0  0]
            [ 0  0  0  0  0  0  0  0  3  1  0  2  0]
            [ 0  0  0  0  0  2  0  0  0  0  0  1  1]]
acc        0.3247863247863248
ari        0.18450866368975685
nmi        0.3645680448060292


Lo

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 18/20 [03:35<00:23, 11.91s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.37994621 0.29175418 0.34923913]
            [0.95406307 0.96415223 0.93555384]
            [0.77981778 0.63743252 0.79961205]]
confusion  [[39  0  0  0  0  6  5  4 10 34  0  0  3]
            [ 4 37  0  1  1 20  4 23  3  0  2  0  9]
            [ 1 17 34 31  0  4 31 14  1  0 18  0  4]
            [ 7  2 46 55  0  0  1  1 10  4 22  0  3]
            [16  0  0  2 68 48 16 17  0  1  1  0 38]
            [ 0 17  0  3 28 21  1  7  1  0  2  0 10]
            [ 0  0  0  0  0  0  1  0  4 11  5  0  0]
            [ 0  0  0  0  0  4  0  2  0  0  0  0  1]
            [ 1  3  0  0  0  0  0  0  6  1  1  0  0]
            [ 4  0  0  0  0  0  0  0 23 28  0  0  0]
            [ 4  0  0  8  0  0  0  0  1  5  5  0  0]
            [ 0  0  0  0  0  0  1  1  3  1  0  0  0]
            [ 0  0  0  0  0  2  1  0  0  0  0  0  1]]
acc        0.3173076923076923
ari        0.18395436692139916
nmi        0.36037179749781373


L

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 19/20 [03:47<00:11, 11.88s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.39156531 0.30274174 0.35041289]
            [0.95125578 0.96526743 0.92332786]
            [0.78908377 0.66023317 0.80338019]]
confusion  [[45  0  0  0  0  7  0  6 11 27  0  4  1]
            [ 5 37  0  0  1 18  3 25  3  0  0  3  9]
            [ 1 17 42 28  0  5 19 14  1  0  0 26  2]
            [ 6  2 52 50  0  0 22  1 11  3  0  1  3]
            [16  0  0  2 67 51  1 18  0  1  0 15 36]
            [ 0 18  0  3 29 22  2  7  0  0  0  1  8]
            [ 1  0  0  0  0  0  6  0  6  8  0  0  0]
            [ 0  0  0  0  0  4  0  2  0  0  0  0  1]
            [ 1  3  0  0  0  0  0  0  6  1  0  0  1]
            [ 4  0  0  0  0  0  0  0 23 28  0  0  0]
            [ 4  0  0  9  0  0  5  0  1  4  0  0  0]
            [ 1  0  0  0  0  0  0  1  3  1  0  0  0]
            [ 0  0  0  0  0  2  0  1  0  0  0  0  1]]
acc        0.3269230769230769
ari        0.18795034145774991
nmi        0.36710068077046043


L

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [03:59<00:00, 11.96s/it]



Metrics    Value
---------  ------------------------------------------
r2         [[0.39842969 0.2967907  0.36261854]
            [0.95700692 0.96644045 0.93694612]
            [0.79665619 0.6456391  0.80570573]]
confusion  [[46  0  0  0  0  7  0  4 10 27  0  5  2]
            [ 5 37  0  0  1 17  4 26  3  0  0  3  8]
            [ 2 17 39 28  0  3 19 15  1  0  0 29  2]
            [ 7  2 51 49  1  0 23  1 10  3  0  1  3]
            [19  0  0  2 67 49  2 17  0  0  0 16 35]
            [ 0 18  0  3 29 22  3  6  0  0  0  2  7]
            [ 0  0  0  0  0  0  7  0  6  8  0  0  0]
            [ 0  0  0  0  0  4  0  2  0  0  0  0  1]
            [ 1  2  0  0  0  0  1  0  7  1  0  0  0]
            [ 4  0  0  0  0  0  0  0 24 27  0  0  0]
            [ 5  0  0  7  0  0  6  0  1  4  0  0  0]
            [ 0  0  0  0  0  0  0  1  3  1  0  1  0]
            [ 0  0  0  0  0  2  0  1  0  0  0  0  1]]
acc        0.32585470085470086
ari        0.18584140966288323
nmi        0.3649860078221325


# Predict on all data

In [38]:

model = UnitedNet(root_save_path, device=device, technique=dbitseq_config)
model.load_model(f"{root_save_path}/train_best.pt",device=torch.device(device))
model.model.device_in_use = device
# model.evaluate(adatas_train,give_losses=False,stage="train")
predict_label = model.predict_label(adatas_all)

print(root_save_path,'ari:',adjusted_rand_score(adatas_all[0].obs['cell_type'],
                    predict_label))

../saved_results/dlpfc_568_dim_22_0.001_0_None_64_16_16_15_15_False_normed ari: 0.26129926394326425


In [26]:
from src.data import create_dataloader
dataloader_test = create_dataloader(
    model.model,
    adatas_train,
    shuffle=False,
    batch_size=model.model.config["train_batch_size"],
)

In [33]:
import torch
model.model.best_head = torch.tensor(7)

In [34]:
from src.scripts import run_evaluate
metrics = run_evaluate(model.model, dataloader_test)

In [35]:
metrics

{'r2': array([[0.23371273, 0.16326781, 0.2111633 ],
        [0.9213446 , 0.94201426, 0.88849843],
        [0.65070852, 0.45468791, 0.66881152]]),
 'confusion': array([[56,  6,  0,  0,  4,  0,  1,  1,  0, 11,  2,  0,  0],
        [ 0, 21, 32,  0, 14,  0,  1, 10,  0,  4,  1,  0,  0],
        [ 2, 12, 43, 42,  4,  1, 15,  4,  0,  1,  0,  0,  0],
        [ 0,  0,  1, 84,  0,  0, 20,  0,  0, 11,  5,  0,  0],
        [14, 19,  2,  0, 41, 59,  1, 29,  0,  0,  0,  0,  0],
        [ 0,  7, 15,  0, 13, 32,  0,  5,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  9,  0,  0,  2,  6,  0,  0],
        [ 0,  2,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  1,  0,  0,  8,  0,  0,  0],
        [10,  0,  0,  0,  0,  0,  2,  0,  0, 19, 13,  0,  0],
        [ 0,  0,  0,  1,  0,  0,  4,  0,  0,  0, 14,  0,  0],
        [ 1,  1,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0],
        [ 0,  1,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int64),
 'acc': 0.4264705882

In [19]:
#smooth and plot results

coord=np.array((list(adatas_all[0].obs['array_row'].astype('int')),
                list(adatas_all[0].obs['array_col'].astype('int')))).T


united_clus=list(predict_label)

coord=np.array((list(adatas_all[0].obs['array_row'].astype('int')),
                list(adatas_all[0].obs['array_col'].astype('int')))).T

nbrs = NearestNeighbors(n_neighbors=5, algorithm='ball_tree').fit(coord)
distances,indices = nbrs.kneighbors(coord)

united_clus_new=[]
for indi,i in enumerate(united_clus):
  np.array(united_clus)[(indices[indi])]
  occurence_count=Counter(np.array(united_clus)[(indices[indi])])
  united_clus_new.append(occurence_count.most_common(1)[0][0])
    

cluster_pl = sns.color_palette('tab20',20)
color_list = [cluster_pl[5],
 cluster_pl[1],
 cluster_pl[2],
 cluster_pl[4],
 cluster_pl[11],
 cluster_pl[6],
 cluster_pl[3],
 cluster_pl[7],
 cluster_pl[8],
 cluster_pl[0]]    

In [1]:
plt.figure(figsize=(6,5))
for idx,clus_id in enumerate(set(united_clus_new)):
    
    plt.scatter(adatas_all[0].obs['array_row'][(united_clus_new==clus_id)],
               adatas_all[0].obs['array_col'][(united_clus_new==clus_id)],
               color=color_list[idx],cmap='tab20')
plt.axis('off')
# plt.savefig('dbitseq.png',dpi=300)